In [2]:
#Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [3]:
#Read the dataset
data = pd.read_csv('C:/Users/Fahad/Desktop/Directory/Fahad/8th sem/ML/gender_submission.csv')

In [6]:
data.head()

PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [7]:
#Data Visualization and Analysis
data.shape

(418, 2)

In [8]:
data['Survived'].value_counts()

0    266
1    152
Name: Survived, dtype: int64

In [9]:
data.columns

Index(['PassengerId', 'Survived'], dtype='object')

In [10]:
data.values

array([[ 892,    0],
       [ 893,    1],
       [ 894,    0],
       [ 895,    0],
       [ 896,    1],
       [ 897,    0],
       [ 898,    1],
       [ 899,    0],
       [ 900,    1],
       [ 901,    0],
       [ 902,    0],
       [ 903,    0],
       [ 904,    1],
       [ 905,    0],
       [ 906,    1],
       [ 907,    1],
       [ 908,    0],
       [ 909,    0],
       [ 910,    1],
       [ 911,    1],
       [ 912,    0],
       [ 913,    0],
       [ 914,    1],
       [ 915,    0],
       [ 916,    1],
       [ 917,    0],
       [ 918,    1],
       [ 919,    0],
       [ 920,    0],
       [ 921,    0],
       [ 922,    0],
       [ 923,    0],
       [ 924,    1],
       [ 925,    1],
       [ 926,    0],
       [ 927,    0],
       [ 928,    1],
       [ 929,    1],
       [ 930,    0],
       [ 931,    0],
       [ 932,    0],
       [ 933,    0],
       [ 934,    0],
       [ 935,    1],
       [ 936,    1],
       [ 937,    0],
       [ 938,    0],
       [ 939,

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
dtypes: int64(2)
memory usage: 6.7 KB


In [12]:
data.describe()

PassengerId    Survived
count   418.000000  418.000000
mean   1100.500000    0.363636
std     120.810458    0.481622
min     892.000000    0.000000
25%     996.250000    0.000000
50%    1100.500000    0.000000
75%    1204.750000    1.000000
max    1309.000000    1.000000

In [14]:
X = data.iloc[:,:1]
X.head()

PassengerId
0          892
1          893
2          894
3          895
4          896

In [21]:
y = data.iloc[:,-1]
y.head()

0    0
1    1
2    0
3    0
4    1
Name: Survived, dtype: int64

In [22]:
#Data Normalization
X = preprocessing.StandardScaler().fit_transform(X)
X[0:1]

array([[-1.72791209]])

In [23]:
#Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test  = train_test_split(X,y,test_size=0.3, random_state=1)

In [24]:
y_test.shape

(126,)

In [26]:
#Training and Predicting
knnmodel = KNeighborsClassifier(n_neighbors = 3)
knnmodel.fit(X_train,y_train)
y_predict = knnmodel.predict(X_test)

In [28]:
#Accuracy
from sklearn.metrics import accuracy_score

In [29]:
acc = accuracy_score(y_test,y_predict)
acc

0.5

In [30]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test.values,y_predict)
cm

array([[55, 30],
       [33,  8]], dtype=int64)

In [31]:
cm1 = pd.DataFrame(data=cm,index=['PassengerId','Survived'],columns=['PassengerID','Survived'])
cm1    
    

PassengerID  Survived
PassengerId           55        30
Survived              33         8

In [33]:
#Output Visualtion
predictionOutput = pd.DataFrame(data=[y_test.values,y_predict],index=['y_test','y_predict'])
predictionOutput.transpose()

y_test  y_predict
0         0          1
1         0          0
2         0          1
3         0          1
4         1          0
..      ...        ...
121       0          0
122       1          0
123       1          0
124       0          0
125       0          0

[126 rows x 2 columns]

In [36]:
predictionOutput.iloc[0,:].value_counts()

0    85
1    41
Name: y_test, dtype: int64

In [39]:
# #Finding the value of K
# Ks=20
# mean_acc = np.zeros((ks-1))
# std_acc = np.zeros((ks-1))